# http://11l-lang.org/
# install gcc8
TARGET   = fizzbuzz
SRC      = $(TARGET).11l
CPP_SRC  = $(TARGET).cpp
COMPILER = ~/Downloads/11l/11l

all:
	$(COMPILER) $(SRC)
	./$(TARGET)

clean:
	rm $(TARGET) $(CPP_SRC)
